[package]
name = "shouldnt-you-be-doing-bot"
version = "0.1.0"
authors = ["Tomoya Tabuchi <t@tomoyat1.com>"]

[dependencies]
chrono = "0.4"
egg-mode = "0.12.0"
futures = "0.2.1"
lazy_static = "1.0"
tokio = "0.1.5"
tokio-core = "0.1.17"
